### ISSUE TITLE
Add embeds from Thatte Idli Kaal soup FB page and Instagram page

### ISSUE THREAD

**Issue by vkrishnaswam** [thatte-idli-kaal-soup/tiks-ultimate.in#1]

**Comment by vkrishnaswam** [comment]
I think instead of adding embed's from the FB page and Instagram page, adding images from the gallery will be useful. Closing this issue.

**Comment by punchagan** [comment]
We could have both, may be. Nice pictures from Instagram can lead to people following us on Insta, which means they stumble on us more often than visiting the site once, and forgetting about it.
