### ISSUE TITLE
Add details of practice sessions

### ISSUE THREAD

**Issue by vkrishnaswam** [thatte-idli-kaal-soup/tiks-ultimate.in#3]
Venue and time with links would be useful for people trying to find us.

**Comment by punchagan** [comment]
wild idea: May be we automatically display pick-ups happening on the site from the RSVP app. :)

**Comment by vkrishnaswam** [comment]
That would be quite cool! I've a feeling this team page can't just be a github page in that case? 🤔

**Comment by punchagan** [comment]
It can. We use js to fetch information from the RSVP app.

**Comment by punchagan** [comment]
We have basic information. Automated fetching of events is an idea for another day
